"""
Django settings for betweencoffee_delivery project.  # 修改这一行

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import logging
import dj_database_url
from pathlib import Path


from environ import Env
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Railway 环境检测
IS_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT') is not None

# 安全密钥配置
if IS_RAILWAY:
    SECRET_KEY = os.environ.get('SECRET_KEY')
else:
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key-for-development-only')

# 调试模式配置
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'


# 域名和主机配置
if IS_RAILWAY:
    # 获取 Railway 分配的主机名
    RAILWAY_STATIC_URL = os.environ.get('RAILWAY_STATIC_URL')
    RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
    
    ALLOWED_HOSTS = []
    if RAILWAY_PUBLIC_DOMAIN:
        ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    if RAILWAY_STATIC_URL:
        ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)
    
    # 添加通用的 Railway 域名
    ALLOWED_HOSTS.extend(['*.railway.app', '.railway.app'])
    
    # CSRF 信任源
    CSRF_TRUSTED_ORIGINS = []
    if RAILWAY_PUBLIC_DOMAIN:
        CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')
    if RAILWAY_STATIC_URL:
        CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_STATIC_URL}')
    CSRF_TRUSTED_ORIGINS.append('https://*.railway.app')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

# 数据库配置 - Railway 适配
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Django Secret Key - 移除硬编码
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key-for-development-only')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-vwi14g!cw8o+^=72zclbmgskh_jrm4h_-^v3u!ti1p)@)p6u)&'

# Render SECRET_KEY: Keub6QImLKq0srBx2mLWEyundshqHFYZ1Agg96_UZ9HH3d-338hcuiJz5tZtMTd7fX8





# SECURITY WARNING: don't run with debug turned on in production!
# 从环境变量读取，生产环境,通过判断是否在 Render 环境来设置[citation:5]
# DEBUG = 'RENDER' not in os.environ

# 临时启用调试 - 完成后务必关闭！
# DEBUG = True
ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['betweencoffee.onrender.com', 'localhost', '127.0.0.1']


# 详细的日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



# 基础Redis配置，从环境变量读取URL，默认为本地开发地址
REDIS_URL = os.environ.get('REDIS_URL', None)  # 允许为 None

if REDIS_URL:
    # 使用 Redis 配置
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            # ... 其他配置
        }
    }
else:
    # 使用内存缓存
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# 修正后的 Channels 配置（保留第 98-104 行，删除第 200-206 行）
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    # 当没有 Redis 时使用内存后端
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# 获取 Render 分配给你的域名并添加到允许列表中
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

CSRF_TRUSTED_ORIGINS = [ 'https://*' ]


# Application definition
INSTALLED_APPS = [
    'eshop',
    'cart',
    'socialuser',
    'channels',
    #'restaurant',
    'crispy_forms',
    'phonenumber_field',
    "django_rename_app",
    

    # Enable allauth social account
    'allauth',
    'allauth.account', # Ensure the version is 0.54.0 or higher.
    'allauth.socialaccount',
    # social account providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',


    # django lib
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_htmx',
]

SITE_ID = 1
SITE_NAME = "Between Coffee"  # Your site name
SITE_DOMAIN = "betweencoffee.com"  # Your production domain


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'betweencoffee_delivery.middleware.CartMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # 处理管理员会话隔离
    'betweencoffee_delivery.middleware.AdminSessionMiddleware',
]

ROOT_URLCONF = 'betweencoffee_delivery.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join (BASE_DIR, 'templates')],
        'APP_DIRS': True,  # This enables Django to find app-specific templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
            ],
        },
    },
]

ASGI_APPLICATION = 'betweencoffee_delivery.asgi.application'

WSGI_APPLICATION = 'betweencoffee_delivery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Database configuration for both development and production



'''
Render
# 开发环境使用本地数据库，生产环境使用 Render 的数据库
# 数据库配置 - 修正版本
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # 本地开发环境
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'betweencoffee_delivery_db',
            'USER': 'postgres',
            'PASSWORD': '111111',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
'''


'''
# 用pg_dump command to 备份数据库
pg_dump -h localhost -p 5432 -U postgres -d betweencoffee_delivery_db -F c -b -v -f backup_$(date +%Y%m%d_%H%M%S).sql
备份数据库date:
14092025
'''


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]




# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# Set your local HK timezone
LANGUAGE_CODE = 'zh-hant'  # 繁体中文
TIME_ZONE = 'Asia/Hong_Kong'  # 香港時區
USE_I18N = True
USE_L10N = True
USE_TZ = True  # Enable timezone support



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


# Static files configuration
# 简化静态文件配置
STATIC_URL = '/static/'
# 对于生产环境，仍然设置 STATIC_ROOT 但指向相同目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 确保静态文件目录存在
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 修改后（Render跳过文件验证）：
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# 生产环境安全配置
if IS_RAILWAY and not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# 移除可能有Render冲突的配置
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]




# 简化 Whitenoise 配置
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ACCOUNT_ADAPTER = 'restaurant.account_adapter.NoNewUsersAccountAdapter'
# LOGIN_REDIRECT_URL = 'dashboard'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Enable Whole cart session
CART_SESSION_ID = 'cart'





# Fully social login tutorial:
# https://www.youtube.com/watch?v=dASjmItZcWE

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('OAUTH_GOOGLE_CLIENT_ID'),
            'secret': env('OAUTH_GOOGLE_SECRET'),
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online', # get access token in session
            'prompt': 'consent',
        },
    },

    'facebook': {
        'APP': {
            'client_id': env('OAUTH_FACEBOOK_CLIENT_ID'),
            'secret': env('OAUTH_FACEBOOK_SECRET'),
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],  # Explicitly request email
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'VERIFIED_EMAIL': True,
    },
}


# Django System Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Real emails testing
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pythonkei@gmail.com' # In google app name : betweencoffee_delivery_email_confirm,

# 邮箱配置 - 使用环境变量
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='fyzl jxbv jndk xajw')
'''
EMAIL_HOST_PASSWORD = 'fyzl jxbv jndk xajw' # NOT your regular password (see note below), gen by google
'''
DEFAULT_FROM_EMAIL = 'pythonkei@gmail.com' # Should match EMAIL_HOST_USER
SERVER_EMAIL = 'pythonkei@gmail.com'  # For error notifications

# Subject prefix for emails
EMAIL_SUBJECT_PREFIX = 'Between Coffee'

# Server email (for error messages)
SERVER_EMAIL = 'pythonkei@gmail.com'





# ===== Social Account Only Configuration =====
# Disable regular account functionality
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disabled for regular accounts
ACCOUNT_ADAPTER = 'socialuser.adapters.NoNewUsersAccountAdapter'

# Social account specific settings
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Social providers verify emails
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_STORE_TOKENS = True  # Recommended for social accounts
SOCIALACCOUNT_LOGIN_ON_GET = True 
ACCOUNT_LOGOUT_ON_GET = True  # Skip confirmation screen
ACCOUNT_UNIQUE_EMAIL = True # Unique for each acc
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True # Trust email valid
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True # Autoconnect and saving social acc already existing in database
SOCIALACCOUNT_EMAIL_VERIFICATION = "none" # No need verify email again if already been verify


# Minimal required settings
ACCOUNT_UNIQUE_EMAIL = True  # Keep email uniqueness
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_LOGIN_ON_GET = True


# User email Verification Settings
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/profile/settings/'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/accounts/login/'
ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = "account/email/email_confirmation"
ACCOUNT_EMAIL_CONFIRMATION_SUBJECT = "account/email/email_confirmation_subject.txt"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Between Coffee] "

# allauth login cancell redirect
SOCIALACCOUNT_TEMPLATES = {
    'login_cancelled': 'socialuser/login_cancelled.html',
}

# 'phonenumber_field' app configs
PHONENUMBER_DEFAULT_REGION = "HK"
PHONENUMBER_DB_FORMAT = "NATIONAL"  # Store without country code


'''
# Show environ的DEBUG输出
logging.basicConfig(level=logging.DEBUG)
'''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',  # 改为INFO级别，减少DEBUG输出
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'environ': {  # 添加这个配置来减少environ的DEBUG输出
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'eshop': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'alipay': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# 支付宝中国配置
ALIPAY_APP_ID = '9021000151625966'

'''
应用公钥：工具生成的公钥需要上传到支付宝的
支付宝公钥：这个是支付宝的公钥
应用私钥：工具生成的应用私钥

https://blog.csdn.net/qq_51738765/article/details/147196238?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_utm_term~default-0-147196238-blog-122902877.235^v43^pc_blog_bottom_relevance_base7&spm=1001.2101.3001.4242.1&utm_relevant_index=2
'''

'''硬编码
# App Private Key PKCS8 Format *one line and remove space
ALIPAY_APP_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4Vyqi5S4iJFW4lfP+wIQTBa2EPPUs47F+1psrRt5rQeULbB4RmwAvqrEnFNrgSoHhK2rRao9hXRIsafSyLI/TIWLa29ngPPtXNZNa7OYem9wOPiJhAAzVqBhPrFLZ7XNX4Gwkr9NkzdVnPdRlqk22YIIdstLfalFOvqegG3FWlzDUm4eouNJYlG0dQlBR/m+jMJ/Q0Sy7aIaidgN5Ph7pxUshXkjHbqIYXsgT7129wFU/W/2wdvUff4GnaEnNBLwZbe7TE73jkLQWylLnO8BfBsXOaCCmXZmGUL/3qVHYAgTUT4Z1XkUdYZw77Li6rSxfYdp+R6ld/4BNnX3SsAFrAgMBAAECggEARpP5Gw0sMJ5Aw7+F/8+twaq22J6OMHWtC6cXGea0WdSM4WavzIXP+HAeC5yMgLuGJrP83dkytFByGNcofN9a4bcypiDutlAi2y0EEhgJs0ZxZnKbrw/Z2iPVywtrXUzwkIC4ZwN6qGm2fyTJIXOm9WDV8JD689c88i1E+KQJLOFnngfFI9vRUpX8b9QzDa/t6TFnDJyga0ftRWLQCn9rvoHPRpjBsFodRUe/CAEtOQR8j+ykJhRhk5lSB1sJ66c0Mj/+IT9SBXorlaQ91cIIdUOak2JL+N6E4BhKXZYUBpOM6STyZQ+/k+dC7fziTIgJ9LwkIwmh+AIfwcAChbo1YQKBgQDkbyrSPmlIlXhJYCGZFnxSZXPhZCGNJ976lb1CYtZzKx1K0QcZT/1e8mnw7Q+Uq8Vv8BCUgpAr5pe+72xPGZoE9lIalWLs26koCtKeQWTaT5nybh9XgwynrNT4F9NqwCbl0kE8pfNBZpR3h+0DbfNgDTw3nUF/OW8n3ghoa2qCPwKBgQDOldjSrgEhYwz34/jlkrquRI89CXCaOy41hPzFCF8zS5j3C70qjt6I0Ro4E+U9zgOnWzLiJxSzWTJ3f9Gv81q4LvEOdsTSH+YRK5jUApn84U8zC26KlcMnUxW7KdG5QdARICeN5r1H1EcixbZUR8ORLffWt0Hw1D/KDTuqoI+d1QKBgQDJOAdvVVymfEuNzukpkb4HUqil1O8dCQ8IithA3xFqN4NBASmQqX5VoZGikR+VZU2wkbX5K51VnnTy0rIEZ1fdoSCnnAmc/M1foVDv6EivaUkBXPGsw5plJQAgXdR0hzh8Xx3qD4BcjsCfHhOwXqzwYhg2IQaty+jXJGUhneUfPwKBgQC2yHq5nd++LKeSxZC5f2PRQTQDa1DIBcjS7cHAi7G/7wl+vFI5T4OyRmEOcPwJ/TfaYaTZ2H5GWYt/lAZxyb3g7Re4Fnn6+OJVGt/z5gFdb/TlUx4RXIT5TFgT6+J2KbbxECQvN5MN9NKj/49dbsmosKVyw16CuSlfmunKBJpNqQKBgH347BjZdeua7gJiMGO/QRJMKEjL9HLB9l0xsg+udxDN/55xmunVVK9kDt337LnSs17f++1Z+YkHjSGOIPpNSgdBiKRSDptQVnQ3bm+Q31WdraqaTUrR3X3YifHkBDUrcqjbnonJlbd/5yK+aows9IgcHvNC3sSRBrtc20z47zXJ
-----END PRIVATE KEY-----"""

# Alipay Public Key from Alipay Sandbox (NOT your application public key)
ALIPAY_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwTKp2l7B+SLjrIWqXeRUYCnH291jq05/fAPcV/bSrZbXRT2vEi9SfypceTaRjnKbsJp8tozYEPHJxqV0Ia4nr4zFixHhlSGJk/uMICC16dkQ3NebHy7PUMJjyu2rhtB4GyvF2HZwlcku21BR2iVMqh5ZO5WNxz0qjx9gbAqk5ebqFktPAPPa86dnoVeHIK4KPs/L3Mfkqc03fypbj/4v1IPKEcmvB2kKnGGrZCoOGvknApJGSQkH3JPN+gpFJEJnnehASd+sRTLTTDG8K/KL8mo2fdwZ/w7APJkkVUzHRLOileFlyijehwapeJ+yJAmvan8lR0oIAsBZlp0+HBIW6QIDAQAB
-----END PUBLIC KEY-----"""
'''


# 支付宝配置 - 使用环境变量
ALIPAY_APP_ID = env('ALIPAY_APP_ID', default='9021000151625966')
ALIPAY_APP_PRIVATE_KEY = env('ALIPAY_APP_PRIVATE_KEY', default='''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4Vyqi5S4iJFW4lfP+wIQTBa2EPPUs47F+1psrRt5rQeULbB4RmwAvqrEnFNrgSoHhK2rRao9hXRIsafSyLI/TIWLa29ngPPtXNZNa7OYem9wOPiJhAAzVqBhPrFLZ7XNX4Gwkr9NkzdVnPdRlqk22YIIdstLfalFOvqegG3FWlzDUm4eouNJYlG0dQlBR/m+jMJ/Q0Sy7aIaidgN5Ph7pxUshXkjHbqIYXsgT7129wFU/W/2wdvUff4GnaEnNBLwZbe7TE73jkLQWylLnO8BfBsXOaCCmXZmGUL/3qVHYAgTUT4Z1XkUdYZw77Li6rSxfYdp+R6ld/4BNnX3SsAFrAgMBAAECggEARpP5Gw0sMJ5Aw7+F/8+twaq22J6OMHWtC6cXGea0WdSM4WavzIXP+HAeC5yMgLuGJrP83dkytFByGNcofN9a4bcypiDutlAi2y0EEhgJs0ZxZnKbrw/Z2iPVywtrXUzwkIC4ZwN6qGm2fyTJIXOm9WDV8JD689c88i1E+KQJLOFnngfFI9vRUpX8b9QzDa/t6TFnDJyga0ftRWLQCn9rvoHPRpjBsFodRUe/CAEtOQR8j+ykJhRhk5lSB1sJ66c0Mj/+IT9SBXorlaQ91cIIdUOak2JL+N6E4BhKXZYUBpOM6STyZQ+/k+dC7fziTIgJ9LwkIwmh+AIfwcAChbo1YQKBgQDkbyrSPmlIlXhJYCGZFnxSZXPhZCGNJ976lb1CYtZzKx1K0QcZT/1e8mnw7Q+Uq8Vv8BCUgpAr5pe+72xPGZoE9lIalWLs26koCtKeQWTaT5nybh9XgwynrNT4F9NqwCbl0kE8pfNBZpR3h+0DbfNgDTw3nUF/OW8n3ghoa2qCPwKBgQDOldjSrgEhYwz34/jlkrquRI89CXCaOy41hPzFCF8zS5j3C70qjt6I0Ro4E+U9zgOnWzLiJxSzWTJ3f9Gv81q4LvEOdsTSH+YRK5jUApn84U8zC26KlcMnUxW7KdG5QdARICeN5r1H1EcixbZUR8ORLffWt0Hw1D/KDTuqoI+d1QKBgQDJOAdvVVymfEuNzukpkb4HUqil1O8dCQ8IithA3xFqN4NBASmQqX5VoZGikR+VZU2wkbX5K51VnnTy0rIEZ1fdoSCnnAmc/M1foVDv6EivaUkBXPGsw5plJQAgXdR0hzh8Xx3qD4BcjsCfHhOwXqzwYhg2IQaty+jXJGUhneUfPwKBgQC2yHq5nd++LKeSxZC5f2PRQTQDa1DIBcjS7cHAi7G/7wl+vFI5T4OyRmEOcPwJ/TfaYaTZ2H5GWYt/lAZxyb3g7Re4Fnn6+OJVGt/z5gFdb/TlUx4RXIT5TFgT6+J2KbbxECQvN5MN9NKj/49dbsmosKVyw16CuSlfmunKBJpNqQKBgH347BjZdeua7gJiMGO/QRJMKEjL9HLB9l0xsg+udxDN/55xmunVVK9kDt337LnSs17f++1Z+YkHjSGOIPpNSgdBiKRSDptQVnQ3bm+Q31WdraqaTUrR3X3YifHkBDUrcqjbnonJlbd/5yK+aows9IgcHvNC3sSRBrtc20z47zXJ
-----END PRIVATE KEY-----''')
ALIPAY_PUBLIC_KEY = env('ALIPAY_PUBLIC_KEY', default='''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwTKp2l7B+SLjrIWqXeRUYCnH291jq05/fAPcV/bSrZbXRT2vEi9SfypceTaRjnKbsJp8tozYEPHJxqV0Ia4nr4zFixHhlSGJk/uMICC16dkQ3NebHy7PUMJjyu2rhtB4GyvF2HZwlcku21BR2iVMqh5ZO5WNxz0qjx9gbAqk5ebqFktPAPPa86dnoVeHIK4KPs/L3Mfkqc03fypbj/4v1IPKEcmvB2kKnGGrZCoOGvknApJGSQkH3JPN+gpFJEJnnehASd+sRTLTTDG8K/KL8mo2fdwZ/w7APJkkVUzHRLOileFlyijehwapeJ+yJAmvan8lR0oIAsBZlp0+HBIW6QIDAQAB
-----END PUBLIC KEY-----''')





ALIPAY_DEBUG = True
ALIPAY_RETURN_URL = 'http://localhost:8080/eshop/alipay_callback/'
ALIPAY_NOTIFY_URL = 'http://localhost:8080/eshop/alipay_notify/'
ALIPAY_SIGN_TYPE = 'RSA2'
ALIPAY_CHARSET = 'utf-8'

'''
# PayPal form 开发者平台
PAYPAL_ENVIRONMENT = 'sandbox'  # 或 'production'
PAYPAL_CLIENT_ID = 'AZPAFBc3xr01Ap4DUkDj0P6pGhPwizG93cXocVlQv-PJQ87BROpjqxxRXgYpI82guz3Aebq9uhvIaUp-'
PAYPAL_CLIENT_SECRET = 'EPwY7G6-uAKNjmDUhy-Awa_HC-MjaU3VHN8d4K4eQ3n67_2ndR_3A8TFrC8O-ZL3QVFIELPlB81XAWwS'
'''


# PayPal 配置 - 使用环境变量
PAYPAL_CLIENT_ID = env('PAYPAL_CLIENT_ID', default='AZPAFBc3xr01Ap4DUkDj0P6pGhPwizG93cXocVlQv-PJQ87BROpjqxxRXgYpI82guz3Aebq9uhvIaUp-')
PAYPAL_CLIENT_SECRET = env('PAYPAL_CLIENT_SECRET', default='EPwY7G6-uAKNjmDUhy-Awa_HC-MjaU3VHN8d4K4eQ3n67_2ndR_3A8TFrC8O-ZL3QVFIELPlB81XAWwS')

'''
# FPS config
FPS_MERCHANT_ID = env('FPS_MERCHANT_ID', default='BETWEENCOFFEE')
FPS_MERCHANT_NAME = 'Between Coffee'
FPS_BANK_ACCOUNT = env('FPS_BANK_ACCOUNT', default='')
FPS_PHONE_NUMBER = env('FPS_PHONE_NUMBER', default='+85212345678')
'''

# FPS 配置 - 使用环境变量
FPS_MERCHANT_ID = env('FPS_MERCHANT_ID', default='BETWEENCOFFEE')
FPS_BANK_ACCOUNT = env('FPS_BANK_ACCOUNT', default='')
FPS_PHONE_NUMBER = env('FPS_PHONE_NUMBER', default='+85212345678')



# ===== 生产环境安全配置 =====
# 检测是否在 Render 生产环境

# 生产环境配置
IS_RENDER = 'RENDER' in os.environ

if IS_RENDER:
    DEBUG = False
    # 确保有正确的主机名
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME, 'betweencoffee.onrender.com']
    else:
        ALLOWED_HOSTS = ['betweencoffee.onrender.com', 'localhost']
    
    # 安全配置
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']







'''
github working
ac: pythonkei@gmail.com
pw: github_123_pass

Developer
name: kei python
ac: heyeahheyeah@yahoo.com.hk
pw: Testing123


Personal (buyer)
ac: sb-btivk46269238@personal.example.com
pw:aD5>kQro

Business (seller)
ac: sb-tmusp46269239@business.example.com
pw:5bR/PiQE

IPN:
Notification URL: http://localhost.com/eshop/order_payment_confirmation/
Message Delivery: Enabled
'''

'''
# Twilio配置（示例）
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')
'''

# Twilio 配置 - 使用环境变量
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')



# 在文件末尾添加配置验证
def check_settings():
    required_env_vars = [
        'SECRET_KEY',
        'DATABASE_URL',
    ]
    
    missing_vars = [var for var in required_env_vars if not os.environ.get(var)]
    if missing_vars:
        print(f"Missing environment variables: {missing_vars}")
    
    # 检查数据库连接
    try:
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1")
        print("Database: OK")
    except Exception as e:
        print(f"Database connection failed: {e}")

# 应用启动时执行检查
check_settings()


# 在settings.py末尾添加
DEBUG_PROPAGATE_EXCEPTIONS = True

'''
twilio
ac: pythonkei@gmail.com
Recovery code: WRNU5SUTXWLZX17UXA9N7Q69
'''



'''
# MessageBird配置（备选）
MESSAGEBIRD_ACCESS_KEY = env('MESSAGEBIRD_ACCESS_KEY', default='')

# Nexmo/Vonage配置（备选）
NEXMO_API_KEY = env('NEXMO_API_KEY', default='')
NEXMO_API_SECRET = env('NEXMO_API_SECRET', default='')
'''


'''
# local test Email Configuration - development only
# Display in console output for the email 
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Emails print to console
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Require email verification
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/profile/settings/' 


ACCOUNT_EMAIL_CONFIRMATION_TEMPLATE = 'account/email/email_confirmation_signup'
ACCOUNT_EMAIL_CONFIRMATION_SUBJECT = "Please verify your email address"
'''


'''
For myself reference

HK Alipay bussiness ac
pythonkei@gmail.com, Password_123
Alipay Sandbox:
https://global.alipay.com/docs/ac/hk_auto_debit/sandbox
https://noter.tw/5445/php-%E4%B8%B2%E6%8E%A5-alipayhk-%E8%B8%A9%E5%9D%91%E8%A8%98%E9%8C%84/



DeepSeek API key
sk-362506ad6b114bf8a9c944bec5e2dd1e

Paypal_pass_829919

Alipay bussiness ac
pythonkei@gmail.com, Password_123
设置支付宝国际账户支付密码:Alipaypass123_

china mobile:
19168604470

csdn account
id:heyeahheyeah


Fully Tutorial for social login (followed):
OAuth - Social Logins with Django and Allauth - Google, Github, X and Facebook
https://www.youtube.com/watch?v=dASjmItZcWE


#FB:
#PassPassPassFB999
#meta for developers ac and my app info:
#app name: kei_production
'''

'''
ollama ac:
pythonkei
pythonkei@gmail.com
'''


'''
Fix E: Unmet dependencies.
https://blog.csdn.net/u013832707/article/details/113104006

Fix error message when run sudo apt
The following packages have unmet dependencies:
 libnvidia-decode-570 : Depends: libnvidia-compute-570 (= 570.124.06-0ubuntu1) but 570.133.07-0ubuntu0.24.04.1 is to be installed
 libnvidia-encode-570 : Depends: libnvidia-decode-570 (>= 570.133.07) but 570.124.06-0ubuntu1 is to be installed
 nvidia-driver-570 : Depends: libnvidia-decode-570 (= 570.133.07-0ubuntu0.24.04.1) but 570.124.06-0ubuntu1 is to be installed
Solution 2:
sudo apt-get install -f
'''
