# Generated by Django 4.2.21 on 2026-03-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialuser', '0002_auto_20251116_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', '銅級會員'), ('silver', '銀級會員'), ('gold', '金級會員'), ('platinum', '白金會員')], default='bronze', max_length=20)),
                ('points', models.IntegerField(default=0, verbose_name='積分')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累計消費')),
                ('total_orders', models.IntegerField(default=0, verbose_name='累計訂單')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='最後訂單日期')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='加入日期')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='折扣率')),
                ('free_upgrade', models.BooleanField(default=False, verbose_name='免費升級杯型')),
                ('priority_service', models.BooleanField(default=False, verbose_name='優先服務')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客戶忠誠度',
                'verbose_name_plural': '客戶忠誠度',
                'indexes': [models.Index(fields=['tier'], name='socialuser__tier_cc902e_idx'), models.Index(fields=['points'], name='socialuser__points_189c0e_idx'), models.Index(fields=['total_spent'], name='socialuser__total_s_7207ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='優惠碼')),
                ('coupon_type', models.CharField(choices=[('percentage', '百分比折扣'), ('fixed', '固定金額'), ('free_item', '免費商品')], max_length=20, verbose_name='優惠類型')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='優惠值')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消費金額')),
                ('valid_from', models.DateTimeField(verbose_name='生效時間')),
                ('valid_to', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('description', models.TextField(blank=True, verbose_name='優惠描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客戶優惠券',
                'verbose_name_plural': '客戶優惠券',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='socialuser__user_id_10e052_idx'), models.Index(fields=['valid_to'], name='socialuser__valid_t_98989d_idx'), models.Index(fields=['code'], name='socialuser__code_ad9cd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('points_earned', '獲得積分'), ('tier_upgraded', '等級升級'), ('reward_redeemed', '兌換獎勵'), ('coupon_used', '使用優惠券'), ('order_placed', '下單成功')], max_length=20, verbose_name='活動類型')),
                ('points_change', models.IntegerField(default=0, verbose_name='積分變化')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加數據')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客戶活動記錄',
                'verbose_name_plural': '客戶活動記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='socialuser__user_id_ec09a7_idx'), models.Index(fields=['activity_type'], name='socialuser__activit_33f002_idx')],
            },
        ),
    ]
