# Generated by Django 4.2.21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0003_customerloyalty_customercoupon_customeractivity'),
    ]

    operations = [
        # 添加新的積分系統字段
        migrations.AddField(
            model_name='customerloyalty',
            name='total_points_earned',
            field=models.IntegerField(default=0, verbose_name='累計獲得積分'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='total_points_spent',
            field=models.IntegerField(default=0, verbose_name='累計使用積分'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='points_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='積分到期日'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='last_points_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最後積分更新時間'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='會員編號'),
        ),
    ]