# Generated by Django 4.2.21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0004_add_points_fields'),
    ]

    operations = [
        # 移除 tier 字段的 NOT NULL 約束
        migrations.AlterField(
            model_name='customerloyalty',
            name='tier',
            field=models.CharField(blank=True, choices=[('bronze', '銅級會員'), ('silver', '銀級會員'), ('gold', '金級會員'), ('platinum', '白金會員')], default='bronze', max_length=20, null=True),
        ),
    ]