# Generated by Django 4.2.21 on 2026-05-26 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialuser', '0006_remove_old_loyalty_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.CharField(max_length=50, verbose_name='獎勵ID')),
                ('reward_name', models.CharField(max_length=100, verbose_name='獎勵名稱')),
                ('points_spent', models.IntegerField(default=0, verbose_name='消耗積分')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兌換時間')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用時間')),
                ('applied_order_id', models.IntegerField(blank=True, null=True, verbose_name='應用訂單ID')),
            ],
            options={
                'verbose_name': '已兌換獎勵',
                'verbose_name_plural': '已兌換獎勵',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='customerloyalty',
            name='socialuser__tier_cc902e_idx',
        ),
        migrations.AlterField(
            model_name='customeractivity',
            name='activity_type',
            field=models.CharField(choices=[('points_earned', '獲得積分'), ('tier_upgraded', '等級升級（已棄用）'), ('reward_redeemed', '兌換獎勵'), ('coupon_used', '使用優惠券'), ('order_placed', '下單成功')], max_length=20, verbose_name='活動類型'),
        ),
        migrations.AlterField(
            model_name='customerloyalty',
            name='points',
            field=models.IntegerField(default=0, verbose_name='當前積分'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['points_expiry_date'], name='socialuser__points__a59c28_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['join_date'], name='socialuser__join_da_6e550a_idx'),
        ),
        migrations.AddField(
            model_name='redeemedreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='redeemedreward',
            index=models.Index(fields=['user', 'is_used'], name='socialuser__user_id_82c3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='redeemedreward',
            index=models.Index(fields=['reward_id'], name='socialuser__reward__03127e_idx'),
        ),
    ]
