# Generated by Django 4.2.21 on 2025-11-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='bean_images/')),
                ('image_index', models.ImageField(blank=True, null=True, upload_to='bean_images/index/', verbose_name='首页图片')),
                ('price_200g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_1kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('grinding_level', models.CharField(choices=[('Non', '免研磨'), ('Light', '細研磨'), ('Medium', '中研磨'), ('Deep', '粗研磨')], default='Non', max_length=10)),
                ('flavor', models.TextField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_shop_hot_item', models.BooleanField(default=False)),
                ('hot_item_order', models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序')),
            ],
            options={
                'verbose_name_plural': 'Bean',
                'ordering': ['hot_item_order', '-list_date'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='coffee_images/')),
                ('image_index', models.ImageField(blank=True, null=True, upload_to='coffee_images/index/', verbose_name='首页图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('origin', models.CharField(blank=True, max_length=30)),
                ('flavor', models.TextField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cup_level', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10)),
                ('milk_level', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Extra', 'Extra')], default='Medium', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('is_shop_hot_item', models.BooleanField(default=False)),
                ('hot_item_order', models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序')),
            ],
            options={
                'verbose_name_plural': 'Coffee',
                'ordering': ['hot_item_order', '-list_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('items', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('normal', '普通訂單'), ('quick', '快速訂單')], default='normal', max_length=10)),
                ('is_quick_order', models.BooleanField(default=False, help_text='優先處理', verbose_name='快速訂單')),
                ('pickup_time', models.CharField(blank=True, max_length=50)),
                ('cup_size', models.CharField(blank=True, max_length=50)),
                ('pickup_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('preparing', '制作中'), ('ready', '已就緒'), ('completed', '已完成')], default='pending', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('paypal', 'PayPal'), ('fps', 'FPS转数快'), ('cash', '现金支付')], default='alipay', max_length=10, verbose_name='支付方式')),
                ('fps_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='FPS参考编号')),
                ('fps_qr_code', models.TextField(blank=True, null=True, verbose_name='FPS二维码')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10)),
                ('product_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cup_level', models.CharField(blank=True, max_length=10, null=True)),
                ('milk_level', models.CharField(blank=True, max_length=10, null=True)),
                ('grinding_level', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
