# Generated by Django 3.2+ on 2025-01-01 00:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeitem',
            name='image_index',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/index/', verbose_name='首页图片'),
        ),
        migrations.AddField(
            model_name='beanitem',
            name='image_index',
            field=models.ImageField(blank=True, null=True, upload_to='bean_images/index/', verbose_name='首页图片'),
        ),
    ]