# Generated by Django 4.2.21 on 2025-11-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beanitem',
            options={'ordering': ['-list_date'], 'verbose_name_plural': 'Bean'},
        ),
        migrations.AlterModelOptions(
            name='coffeeitem',
            options={'ordering': ['-list_date'], 'verbose_name_plural': 'Coffee'},
        ),
        migrations.RemoveField(
            model_name='beanitem',
            name='hot_item_order',
        ),
        migrations.RemoveField(
            model_name='beanitem',
            name='image_index',
        ),
        migrations.RemoveField(
            model_name='coffeeitem',
            name='hot_item_order',
        ),
    ]
