# Generated by Django 4.2.21 on 2025-11-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_beanitem_options_alter_coffeeitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beanitem',
            options={'ordering': [], 'verbose_name_plural': 'Bean'},
        ),
        migrations.AlterModelOptions(
            name='coffeeitem',
            options={'ordering': [], 'verbose_name_plural': 'Coffee'},
        ),
    ]
