# Generated by Django 4.2.21 on 2025-11-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_alter_beanitem_options_alter_coffeeitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beanitem',
            name='hot_item_order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序'),
        ),
        migrations.AddField(
            model_name='coffeeitem',
            name='hot_item_order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序'),
        ),
    ]
