# Generated by Django 4.2.21 on 2025-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_beanitem_hot_item_order_coffeeitem_hot_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='last_payment_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后支付尝试时间'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='支付尝试次数'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_timeout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付超时时间'),
        ),
    ]
