# Generated by Django 4.2.21 on 2025-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_alter_ordermodel_payment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='last_payment_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['payment_status', 'payment_timeout'], name='eshop_order_payment_2065e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['created_at', 'payment_status'], name='eshop_order_created_492eca_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['user', 'payment_status'], name='eshop_order_user_id_3cdada_idx'),
        ),
    ]
