# Generated by Django 4.2.4 on 2025-02-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_remove_ordermodel_price_alter_ordermodel_created_at'),
        ('eshop', '0006_auto_20250223_1857'),
    ]

    operations = [
    ]
