# Generated by Django 4.2.4 on 2025-02-23 11:08

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('eshop', '0007_merge_20250223_1902'),  # Depends on the previous migration
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE eshop_ordermodel ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;',
            reverse_sql='ALTER TABLE eshop_ordermodel DROP COLUMN created_at;',
        ),
    ]


'''
How to Fix Column Does not Exist Exception/Error in PostgreSQL

Option 1: Using pgAdmin
Right-click on the eshop_ordermodel table and select Query Tool.

1. Run the following SQL command to add the created_at column:
ALTER TABLE eshop_ordermodel ADD COLUMN created_at
TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

2. then run
python manage.py makemigrations eshop --empty

3. lastest migrate file ex. 0007_merge_20250223_1902
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('eshop', '0007_merge_20250223_1902'),  # Depends on the previous migration
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE eshop_ordermodel ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;',
            reverse_sql='ALTER TABLE eshop_ordermodel DROP COLUMN created_at;',
        ),
    ]

4. then run fake migrate file
python manage.py migrate --fake eshop 0008_auto_20250223_1908
'''