# Generated by Django 4.2.4 on 2025-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20250223_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeitem',
            name='milk_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('E', 'Extra')], default='M', max_length=1),
        ),
    ]
