# Generated by Django 4.2.21 on 2025-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_ordermodel_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['updated_at'], name='eshop_order_updated_78cf76_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['status', 'updated_at'], name='eshop_order_status_760184_idx'),
        ),
    ]
