# Generated by Django 4.2.21 on 2025-12-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_ordermodel_eshop_order_updated_78cf76_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在岗')),
                ('efficiency_factor', models.FloatField(default=1.0, help_text='1.0为正常，<1.0为较快，>1.0为较慢', verbose_name='效率因子')),
                ('max_concurrent_orders', models.PositiveIntegerField(default=3, verbose_name='最大并发订单数')),
                ('current_load', models.PositiveIntegerField(default=0, verbose_name='当前负载')),
            ],
            options={
                'verbose_name': '咖啡师',
                'verbose_name_plural': '咖啡师',
            },
        ),
        migrations.CreateModel(
            name='CoffeePreparationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(max_length=100, verbose_name='咖啡类型')),
                ('base_preparation_minutes', models.PositiveIntegerField(default=5, verbose_name='基础制作时间(分钟)')),
                ('additional_per_cup_minutes', models.PositiveIntegerField(default=3, verbose_name='每增加一杯额外时间(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '咖啡制作时间配置',
                'verbose_name_plural': '咖啡制作时间配置',
            },
        ),
        migrations.CreateModel(
            name='CoffeeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='队列位置')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('preparing', '制作中'), ('ready', '已就緒'), ('completed', '已完成')], default='waiting', max_length=20)),
                ('estimated_start_time', models.DateTimeField(blank=True, null=True, verbose_name='预计开始时间')),
                ('estimated_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('barista', models.CharField(blank=True, max_length=100, null=True, verbose_name='制作人员')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('coffee_count', models.PositiveIntegerField(default=0, verbose_name='咖啡杯数')),
                ('preparation_time_minutes', models.PositiveIntegerField(default=0, verbose_name='预计制作时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='eshop.ordermodel')),
            ],
            options={
                'verbose_name': '咖啡制作队列',
                'verbose_name_plural': '咖啡制作队列',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['status', 'position'], name='eshop_coffe_status_212322_idx'), models.Index(fields=['estimated_completion_time'], name='eshop_coffe_estimat_548772_idx')],
            },
        ),
    ]
