# Generated by Django 4.2.4 on 2025-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_alter_beanitem_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='cup_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('normal', '普通订单'), ('quick', '快速订单')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='beanitem',
            name='roast_level',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Deep', 'Deep')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='cup_level',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='milk_level',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Extra', 'Extra')], default='Medium', max_length=10),
        ),
    ]
