# Generated by Django 4.2.21 on 2026-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_simplify_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pickup_time_choice',
            field=models.CharField(choices=[('5', '5 分鐘後'), ('10', '10 分鐘後'), ('15', '15 分鐘後'), ('20', '20 分鐘後'), ('30', '30 分鐘後'), ('45', '45 分鐘後'), ('60', '1 小時後'), ('custom', '自定時間')], default='5', max_length=10, verbose_name='取餐時間選項'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pickup_time_custom',
            field=models.TimeField(blank=True, help_text='格式: HH:MM (24小時制)', null=True, verbose_name='自定取餐時間'),
        ),
    ]
