# Generated by Django 4.2.21 on 2026-01-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_add_pickup_time_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='pickup_time_choice',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pickup_time_custom',
        ),
    ]
