# Generated by Django 4.2.4 on 2025-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_alter_beanitem_options_alter_coffeeitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
