# Generated by Django 4.2.21 on 2026-02-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_add_pickup_time_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beanitem',
            old_name='price_1kg',
            new_name='price_500g',
        ),
    ]
