# Generated by Django 4.2.21 on 2026-02-14 07:11

from django.db import migrations, models
import secrets
import string


def convert_6_digit_codes_to_4_digits(apps, schema_editor):
    """
    将现有的6位提取码转换为4位数字
    策略：取前4位数字，如果不足4位则补0，如果包含字母则转换为数字
    """
    OrderModel = apps.get_model('eshop', 'OrderModel')
    
    # 获取所有6位提取码的订单
    orders_with_6_digit = OrderModel.objects.filter(
        pickup_code__regex=r'^.{6}$'
    )
    
    print(f"找到 {orders_with_6_digit.count()} 个6位提取码的订单")
    
    for order in orders_with_6_digit:
        old_code = order.pickup_code
        if not old_code or len(old_code) != 6:
            continue
            
        # 尝试将6位码转换为4位数字
        # 方法1：提取所有数字，取前4位
        digits = ''.join([c for c in old_code if c.isdigit()])
        
        if len(digits) >= 4:
            # 有足够数字，取前4位
            new_code = digits[:4]
        else:
            # 数字不足，使用哈希方法生成4位数字
            # 使用订单ID和旧码生成一个稳定的4位数字
            import hashlib
            hash_input = f"{order.id}{old_code}".encode()
            hash_digest = hashlib.md5(hash_input).hexdigest()
            # 从哈希中提取4位数字
            hash_digits = ''.join([c for c in hash_digest if c.isdigit()])
            if len(hash_digits) >= 4:
                new_code = hash_digits[:4]
            else:
                # 最后的手段：生成随机4位数字
                new_code = ''.join(
                    secrets.choice(string.digits) for _ in range(4)
                )
        
        # 确保新码是4位数字
        if len(new_code) != 4 or not new_code.isdigit():
            # 如果还不是4位数字，生成随机4位数字
            new_code = ''.join(
                secrets.choice(string.digits) for _ in range(4)
            )
        
        # 检查新码是否已存在
        while OrderModel.objects.exclude(id=order.id).filter(
            pickup_code=new_code
        ).exists():
            # 如果冲突，生成新的随机码
            new_code = ''.join(
                secrets.choice(string.digits) for _ in range(4)
            )
        
        order.pickup_code = new_code
        order.save(update_fields=['pickup_code'])
        print(f"订单 {order.id}: {old_code} -> {new_code}")


def reverse_convert_codes(apps, schema_editor):
    """
    回滚函数：由于无法恢复原始6位码，我们只记录信息
    在实际回滚时，我们会将字段改回max_length=6
    """
    print("回滚：将pickup_code字段改回max_length=6，但无法恢复原始6位码")


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0021_add_query_optimization_indexes'),
    ]

    operations = [
        # 首先转换现有的6位提取码为4位数字
        migrations.RunPython(
            convert_6_digit_codes_to_4_digits, 
            reverse_convert_codes
        ),
        
        # 然后修改字段长度从6改为4
        migrations.AlterField(
            model_name='ordermodel',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
