# Generated by Django 3.2 on 2025-02-15 16:00
"""
数据迁移：完全移除弃用字段
- 移除 OrderModel 中的弃用字段引用
- 清理相关的属性和方法
- 更新索引和约束
"""

from django.db import migrations
import warnings


def remove_deprecated_fields(apps, schema_editor):
    """
    移除弃用字段的实际数据迁移
    注意：此操作不可逆，建议先备份数据
    """
    try:
        # 1. 确认没有代码还在使用这些字段
        # 2. 此迁移主要是为了清理数据库层面的字段
        # 实际字段已在之前的迁移中移除，这里只是确认
        print("✅ 弃用字段已在之前迁移中移除，此操作为确认性迁移")
    except Exception as e:
        warnings.warn(f"移除弃用字段时出现警告: {e}")


class Migration(migrations.Migration):
    """
    移除弃用字段的最终迁移
    步骤：
    1. 确认已无代码依赖这些字段
    2. 清理残留的索引
    3. 验证数据完整性
    """

    dependencies = [
        ('eshop', '0022_change_pickup_code_to_4_digits'),
    ]

    operations = [
        migrations.RunPython(
            remove_deprecated_fields,
            reverse_code=migrations.RunPython.noop
        ),
        # 移除旧的索引（如果之前迁移未完成）
        migrations.AlterIndexTogether(
            name='coffeequeue',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='ordermodel',
            index_together=set(),
        ),
    ]