# Generated by Django 4.2.21 on 2025-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_ordermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=80, null=True),
        ),
    ]
