# Generated by Django 4.2.21 on 2025-08-29 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0024_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='roast_level',
            new_name='grinding_level',
        ),
        migrations.RemoveField(
            model_name='beanitem',
            name='roast_level',
        ),
        migrations.AddField(
            model_name='beanitem',
            name='grinding_level',
            field=models.CharField(choices=[('Non', '免研磨'), ('Light', '細研磨'), ('Medium', '中研磨'), ('Deep', '粗研磨')], default='Non', max_length=10),
        ),
        migrations.AddField(
            model_name='beanitem',
            name='price_1kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='beanitem',
            name='price_200g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pickup_code',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('preparing', '制作中'), ('ready', '已就绪'), ('completed', '已完成')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product_type', 'product_id', 'cup_level', 'milk_level', 'grinding_level')},
        ),
    ]
