# Generated by Django 4.2.21 on 2026-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0024_add_missing_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="coffeequeue",
            name="idx_queue_status_position",
        ),
        migrations.RemoveIndex(
            model_name="coffeequeue",
            name="idx_queue_est_start",
        ),
        migrations.RemoveIndex(
            model_name="coffeequeue",
            name="eshop_coffeequeue_updated_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="idx_order_quick_status",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="idx_order_payment_created",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="idx_order_pickup_choice",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="eshop_ordermodel_status_payment_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="eshop_ordermodel_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="eshop_ordermodel_status_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordermodel",
            name="eshop_ordermodel_payment_status_idx",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
    ]
