# Generated by Django 4.2.21 on 2026-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0025_add_paid_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='應用優惠碼'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='applied_reward_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='應用獎勵ID'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='applied_reward_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='應用獎勵名稱'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='優惠券折扣金額'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='會員折扣金額'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='loyalty_discount_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='會員折扣率'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='original_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='原始總價'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='reward_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='獎勵折扣金額'),
        ),
    ]
