# Generated by Django 4.2.21 on 2025-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_remove_beanitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
