# Generated by Django 4.2.21 on 2025-08-30 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0027_cartitem_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product_type', 'product_id', 'cup_level', 'milk_level', 'grinding_level', 'weight')},
        ),
    ]
