# Generated by Django 4.2.21 on 2025-08-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0028_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
