# Generated by Django 4.2.21 on 2026-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0029_alter_coffeequeue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="strength_level",
            field=models.CharField(
                choices=[("Regular", "Regular"), ("Extra", "Extra")],
                default="Regular",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "待支付"),
                    ("payment_pending", "付款待確認"),
                    ("paid", "已支付"),
                    ("cancelled", "已取消"),
                    ("expired", "已過期"),
                ],
                default="pending",
                max_length=20,
                verbose_name="支付状态",
            ),
        ),
    ]
