# Generated by Django 4.2.21 on 2026-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0030_coffeeitem_strength_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='strength_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
