# Generated by Django 4.2.21 on 2026-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0033_add_position_to_coffeequeue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='strength_level',
        ),
        migrations.RemoveField(
            model_name='coffeeitem',
            name='strength_level',
        ),
    ]
