# Generated by Django 4.2.21 on 2025-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0033_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beanitem',
            name='image_index',
            field=models.ImageField(blank=True, null=True, upload_to='bean_images/index/', verbose_name='首页图片'),
        ),
        migrations.AddField(
            model_name='coffeeitem',
            name='image_index',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/index/', verbose_name='首页图片'),
        ),
    ]
