# Generated by Django 4.2.21 on 2026-07-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0034_remove_cartitem_strength_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="name",
        ),
    ]
