# Generated by Django 4.2.21 on 2025-11-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0036_ordermodel_fps_qr_code_ordermodel_fps_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
