# Generated by Cline - 新增 CoffeeQueue 缺失的欄位 + 修復 CartItem.updated_at nullable 問題
# 比對 Django model (eshop/models.py) vs 資料庫實際結構

from django.db import migrations, models
import django.utils.timezone


def set_cartitem_updated_at_default(apps, schema_editor):
    """將 eshop_cartitem 中 NULL 的 updated_at 設為 created_at 的值"""
    CartItem = apps.get_model('eshop', 'CartItem')
    db_alias = schema_editor.connection.alias
    CartItem.objects.using(db_alias).filter(updated_at__isnull=True).update(
        updated_at=django.utils.timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0038_add_missing_order_model_fields'),
    ]

    operations = [
        # ===== CoffeeQueue 缺少的欄位 =====
        # 1. estimated_completion_time
        migrations.AddField(
            model_name='coffeequeue',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='預計完成時間'),
        ),
        # 2. actual_completion_time
        migrations.AddField(
            model_name='coffeequeue',
            name='actual_completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='實際完成時間'),
        ),
        # 3. coffee_count
        migrations.AddField(
            model_name='coffeequeue',
            name='coffee_count',
            field=models.PositiveIntegerField(default=1, verbose_name='咖啡杯數'),
        ),
        # 4. preparation_time_minutes
        migrations.AddField(
            model_name='coffeequeue',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='製作時間(分鐘)'),
        ),
        # 5. added_at
        migrations.AddField(
            model_name='coffeequeue',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='加入時間'),
        ),
        # ===== 修復 CartItem.updated_at nullable 問題 =====
        # 先將 NULL 值設為預設值
        migrations.RunPython(
            set_cartitem_updated_at_default,
            reverse_code=migrations.RunPython.noop,
        ),
        # 再改為 non-nullable
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
