# Generated by Cline - 修復 CoffeeQueue.barista 欄位型態不一致問題
# Django model 定義為 CharField，但資料庫中曾是 ForeignKey('Barista')
# 注意：barista 欄位轉換已在資料庫中完成（barista VARCHAR 已存在，barista_id 已被刪除）
# 此 migration 僅用 SeparateDatabaseAndState 同步 Django state

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0039_add_missing_coffeequeue_fields_and_fix_cartitem"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="coffeequeue",
                    name="barista",
                    field=models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="咖啡師"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
