# Generated by Cline - 修復 CoffeeQueue.barista 欄位型態不一致問題
# Django model 定義為 CharField，但資料庫中是 ForeignKey('Barista')
# 需要移除 FK 約束並將 barista_id 改為 VARCHAR barista

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0039_add_missing_coffeequeue_fields_and_fix_cartitem'),
    ]

    operations = [
        # Step 1: 新增 barista VARCHAR 欄位（暫名 barista_new）
        migrations.RunSQL(
            """
            ALTER TABLE eshop_coffeequeue ADD COLUMN IF NOT EXISTS barista_new VARCHAR(100) NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: 將 barista_id FK 轉換為 barista name
        migrations.RunSQL(
            """
            UPDATE eshop_coffeequeue q
            SET barista_new = b.name
            FROM eshop_barista b
            WHERE q.barista_id = b.id
              AND (q.barista_new IS NULL OR q.barista_new = '')
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: 移除 FK 約束
        migrations.RunSQL(
            "ALTER TABLE eshop_coffeequeue DROP CONSTRAINT IF EXISTS eshop_coffeequeue_barista_id_143b226f_fk_eshop_barista_id",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 4: 刪除舊的 barista 欄位（如果存在）
        migrations.RunSQL(
            "ALTER TABLE eshop_coffeequeue DROP COLUMN IF EXISTS barista",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 5: 刪除 barista_id 欄位
        migrations.RunSQL(
            "ALTER TABLE eshop_coffeequeue DROP COLUMN IF EXISTS barista_id",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 6: 將 barista_new 改名為 barista
        migrations.RunSQL(
            "ALTER TABLE eshop_coffeequeue RENAME COLUMN barista_new TO barista",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
