# Generated by Cline - 修復 CoffeeQueue.added_at NOT NULL 約束
# 資料庫中 added_at 已設為 NOT NULL，此 migration 僅用於記錄狀態

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0040_fix_coffeequeue_barista_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeequeue',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入隊列時間'),
        ),
    ]
