# Generated by Django 4.2.21 on 2026-07-18 14:45
# Modified by Cline: 移除 database_operations 中的 RunSQL，因為 discount 欄位在資料庫中可能不存在
# 使用 SeparateDatabaseAndState 只同步 Django state

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0042_alter_coffeequeue_actual_completion_time_and_more"),
    ]

    operations = [
        # 使用 SeparateDatabaseAndState 來同步資料庫與 model 狀態
        # 資料庫中可能已有 discount 欄位（手動添加），但 Django migration state 不知道
        # 這裡告訴 Django：欄位已存在，只需更新 state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="ordermodel",
                    name="discount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="折扣金額",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
