# Generated by Django 4.2.21 on 2026-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0043_add_discount_field_to_ordermodel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordermodel',
                    name='order_number',
                    field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='訂單編號'),
                ),
            ],
            # 資料庫中已有 order_number 欄位（手動添加），
            # 所以不需要執行 database_operations
            database_operations=[],
        ),
    ]
