# Generated by Django 4.x - 同步資料庫殘留欄位到 Django state
# 這些欄位已在資料庫中存在，但 Django model 沒有定義
# 使用 SeparateDatabaseAndState 只同步 state，不修改資料庫

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0044_add_order_number_field_to_ordermodel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordermodel',
                    name='extra_info',
                    field=models.TextField(blank=True, null=True, verbose_name='額外資訊'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='completed_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='完成時間'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='coupon_code',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='優惠碼（舊版）'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='note',
                    field=models.TextField(blank=True, null=True, verbose_name='備註'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='payment_id',
                    field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付ID'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='pickup_time',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='取貨時間（舊版）'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='subtotal',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='小計（舊版）'),
                ),
                migrations.AddField(
                    model_name='ordermodel',
                    name='total',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='總計（舊版）'),
                ),
            ],
            database_operations=[],
        ),
    ]
