# Generated by Django 4.2.21 on 2026-07-19 11:05
# Modified by Cline: RemoveField('pickup_time') 改為 SeparateDatabaseAndState
# 因為 pickup_time 欄位在資料庫中不存在（0045 的 AddField 只更新了 Django state）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0045_sync_legacy_db_fields'),
    ]

    operations = [
        # pickup_time 在資料庫中不存在（0045 的 AddField 只更新了 Django state），
        # 所以 RemoveField 需要改為 SeparateDatabaseAndState 只更新 state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='ordermodel',
                    name='pickup_time',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='coffeequeue',
            name='is_expedited',
            field=models.BooleanField(default=False, verbose_name='是否加速'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='小計（舊版）'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='總計（舊版）'),
        ),
    ]
