# Generated by Django 4.2.21 on 2026-07-19

"""
Migration 0047: Fix Barista table schema to match Django models.

Problem: The eshop_barista table in Supabase was created manually with old column names:
  - is_available (should be is_active)
  - current_workload (should be current_load)
  - max_concurrent (should be max_concurrent_orders)
  - missing: efficiency_factor

This migration renames columns and adds the missing field.

IMPORTANT: Uses SeparateDatabaseAndState because the database columns may already
have been renamed (e.g., on Render/Supabase), while the Django model state already
uses the new field names. This ensures both database and state are in sync.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0046_add_is_expedited_to_coffeequeue"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Rename is_available -> is_active (if column still exists)
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='is_available'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN is_available TO is_active;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='is_active'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN is_active TO is_available;
                        END IF;
                    END $$;
                    """,
                ),
                # Rename current_workload -> current_load (if column still exists)
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='current_workload'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN current_workload TO current_load;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='current_load'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN current_load TO current_workload;
                        END IF;
                    END $$;
                    """,
                ),
                # Rename max_concurrent -> max_concurrent_orders (if column still exists)
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='max_concurrent'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN max_concurrent TO max_concurrent_orders;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='max_concurrent_orders'
                        ) THEN
                            ALTER TABLE eshop_barista RENAME COLUMN max_concurrent_orders TO max_concurrent;
                        END IF;
                    END $$;
                    """,
                ),
                # Add missing efficiency_factor field (if not exists)
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='efficiency_factor'
                        ) THEN
                            ALTER TABLE eshop_barista ADD COLUMN efficiency_factor double precision DEFAULT 1.0 NOT NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name='eshop_barista' AND column_name='efficiency_factor'
                        ) THEN
                            ALTER TABLE eshop_barista DROP COLUMN efficiency_factor;
                        END IF;
                    END $$;
                    """,
                ),
            ],
            state_operations=[
                # State operations: no-op for renames since models.py already uses new names.
                # We use AlterField to ensure Django's state matches the model.
                migrations.AlterField(
                    model_name="barista",
                    name="is_active",
                    field=models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                migrations.AlterField(
                    model_name="barista",
                    name="current_load",
                    field=models.IntegerField(default=0, verbose_name="当前工作量"),
                ),
                migrations.AlterField(
                    model_name="barista",
                    name="max_concurrent_orders",
                    field=models.IntegerField(default=2, verbose_name="最大同时制作量"),
                ),
                migrations.AddField(
                    model_name="barista",
                    name="efficiency_factor",
                    field=models.FloatField(
                        default=1.0,
                        help_text="1.0为正常，<1.0为较快，>1.0为较慢",
                        verbose_name="效率因子",
                    ),
                ),
            ],
        ),
    ]
