# Generated by Django 4.2.21 on 2026-07-20 00:08
# 修復：在資料庫中實際添加 order_number 欄位
#
# 問題背景：
# migration 0044 使用 SeparateDatabaseAndState(database_operations=[])
# 只更新了 Django state，但沒有在資料庫中實際建立 order_number 欄位。
# 這導致 OrderModel.save() 調用 generate_order_number() 時，
# 查詢 order_number__startswith=prefix 會報錯：
#   column eshop_ordermodel.order_number does not exist
#
# 此 migration 在資料庫中實際添加 order_number 欄位。
# 如果欄位已存在（如本地開發環境），PostgreSQL 會忽略此操作。
#
# 注意：依賴 0046 而非 0047，因為 Render 上的資料庫可能沒有 0047。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0046_add_is_expedited_to_coffeequeue"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="order_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="訂單編號",
            ),
        ),
    ]
