# Generated by Django 4.2.21 on 2026-07-20 12:36
# 修復：在資料庫中實際添加 discount 欄位
# 
# 問題背景：
# migration 0043 使用 SeparateDatabaseAndState(database_operations=[])
# 只更新了 Django state，但沒有在資料庫中實際建立 discount 欄位。
# 這導致 OrderModel.save() 或其他查詢用到 discount 欄位時報錯：
#   column eshop_ordermodel.discount does not exist
#
# 此 migration 在資料庫中實際添加 discount 欄位。
# 如果欄位已存在（如本地開發環境），PostgreSQL 會忽略此操作。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0048_add_order_number_column_to_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='折扣金額'),
        ),
    ]
