# Generated by Django 4.2.21 on 2026-07-20 12:56
# 修復：在資料庫中實際添加 migration 0045 跳過的欄位
#
# 問題背景：
# migration 0045 使用 SeparateDatabaseAndState(database_operations=[])
# 只更新了 Django state，但沒有在資料庫中實際建立以下欄位：
#   - extra_info, completed_at, coupon_code, note, payment_id
#   - pickup_time, subtotal, total
#
# 這導致 OrderModel.save() 或其他查詢用到這些欄位時報錯：
#   column eshop_ordermodel.extra_info does not exist
#
# 此 migration 在資料庫中實際添加這些欄位。
# 如果欄位已存在（如本地開發環境），PostgreSQL 會忽略此操作。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0049_add_discount_column_to_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="extra_info",
            field=models.TextField(blank=True, null=True, verbose_name="額外資訊"),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成時間"),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="coupon_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="優惠碼（舊版）"
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="備註"),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="支付ID"
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="pickup_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="取貨時間（舊版）"
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="subtotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="小計（舊版）",
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="總計（舊版）",
            ),
        ),
    ]
