# Generated by Django 4.2.21 on 2026-07-20 13:55
# Merge migration: 合併 0047 (Barista 欄位重命名) 和 0050 (添加 OrderModel 欄位) 兩個分支
# 
# 問題背景：
# 0050 最初依賴 0047，但 Render 上 0050 先被應用（當時 0047 還不存在），
# 導致 InconsistentMigrationHistory。移除 0050 對 0047 的 dependency 後，
# 0047 和 0050 成為兩個 leaf node，需要 merge migration 解決衝突。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0047_fix_barista_table_schema'),
        ('eshop', '0050_add_missing_columns_from_0045_to_db'),
    ]

    operations = [
    ]
