# Generated by Django 4.2.21 on 2026-07-20 14:25
# Modified: 使用 SeparateDatabaseAndState 只更新 Django state，不修改資料庫
#
# 問題背景：
# - models.py 中 pickup_time 同時有 models.DateTimeField 定義和 @property 覆蓋
# - Django autodetector 看到的是 @property，所以認為需要移除 state 中的 pickup_time 欄位
# - 但資料庫中確實有 pickup_time 欄位（由 0050 添加），移除它會導致資料丟失
# - 所以使用 SeparateDatabaseAndState 只更新 state，保留資料庫欄位

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0051_merge_0047_and_0050"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # 不修改資料庫
            state_operations=[
                # 只更新 Django state：移除 pickup_time 欄位
                # 資料庫中的 pickup_time 欄位保持不變
                migrations.RemoveField(
                    model_name="ordermodel",
                    name="pickup_time",
                ),
                # 同步欄位定義：讓 state 中的欄位定義與 model 一致
                migrations.AlterField(
                    model_name="barista",
                    name="current_load",
                    field=models.PositiveIntegerField(
                        default=0, verbose_name="当前负载"
                    ),
                ),
                migrations.AlterField(
                    model_name="barista",
                    name="is_active",
                    field=models.BooleanField(default=True, verbose_name="是否在岗"),
                ),
                migrations.AlterField(
                    model_name="barista",
                    name="max_concurrent_orders",
                    field=models.PositiveIntegerField(
                        default=3, verbose_name="最大并发订单数"
                    ),
                ),
                migrations.AlterField(
                    model_name="coffeequeue",
                    name="barista",
                    field=models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制作人员"
                    ),
                ),
                migrations.AlterField(
                    model_name="ordermodel",
                    name="subtotal",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="小計（舊版）",
                    ),
                ),
                migrations.AlterField(
                    model_name="ordermodel",
                    name="total",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="總計（舊版）",
                    ),
                ),
            ],
        ),
    ]
