# Generated by Cline - 為 CoffeeQueue.coffee_count 和 preparation_time_minutes 設定資料庫層級 default 值
# 修復 "null value in column "coffee_count" violates not-null constraint" 錯誤
# 根因：Migration 0039 使用 SeparateDatabaseAndState + database_operations=[]，
# 導致資料庫層級沒有設定 default 值

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0052_remove_ordermodel_pickup_time_and_more'),
    ]

    operations = [
        # 為 coffee_count 設定資料庫層級 default 值
        migrations.RunSQL(
            sql="ALTER TABLE eshop_coffeequeue ALTER COLUMN coffee_count SET DEFAULT 1;",
            reverse_sql="ALTER TABLE eshop_coffeequeue ALTER COLUMN coffee_count DROP DEFAULT;",
        ),
        # 為 preparation_time_minutes 設定資料庫層級 default 值
        migrations.RunSQL(
            sql="ALTER TABLE eshop_coffeequeue ALTER COLUMN preparation_time_minutes SET DEFAULT 5;",
            reverse_sql="ALTER TABLE eshop_coffeequeue ALTER COLUMN preparation_time_minutes DROP DEFAULT;",
        ),
    ]
