# Generated by Django 4.2.21 on 2026-07-26 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eshop", "0053_add_coffeequeue_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="strength_level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="strength_level",
            field=models.CharField(
                choices=[("Normal", "預設"), ("Extra", "特濃")],
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                (
                    "user",
                    "product_type",
                    "product_id",
                    "cup_level",
                    "milk_level",
                    "strength_level",
                    "grinding_level",
                    "weight",
                )
            },
        ),
    ]
