# Generated by Django 4.2.21 on 2026-07-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0054_alter_cartitem_options_cartitem_strength_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("order_waiting", "標記為等待中"),
                            ("order_preparing", "開始製作"),
                            ("order_ready", "標記為就緒"),
                            ("order_completed", "標記為已完成"),
                            ("order_cancelled", "取消訂單"),
                            ("payment_fps_confirmed", "FPS 付款確認"),
                            ("payment_cash_confirmed", "現金付款確認"),
                            ("payment_auto_paid", "自動支付成功"),
                            ("order_created", "訂單建立"),
                            ("order_updated", "訂單更新"),
                            ("whatsapp_notified", "WhatsApp 通知已發送"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "staff_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="員工名稱",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="包含舊狀態、新狀態等JSON格式的詳細資訊",
                        verbose_name="詳細資訊",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="eshop.ordermodel",
                        verbose_name="相關訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "審計日誌",
                "verbose_name_plural": "審計日誌",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_action_date_idx"
                    ),
                    models.Index(
                        fields=["staff_name", "created_at"], name="audit_staff_date_idx"
                    ),
                ],
            },
        ),
    ]