# Generated by Django 4.2.21 on 2026-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0055_ordermodel_pickup_time_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="beanitem",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="數字越小顯示越靠前", verbose_name="菜單排序"
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="數字越小顯示越靠前", verbose_name="菜單排序"
            ),
        ),
        # 註：ordermodel.pickup_time 已在資料庫存在（0052 移除後手動重建），
        #     故不重複 AddField；此 migration 僅新增 sort_order。
    ]
