# Generated by Django 4.2.21 on 2026-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0056_beanitem_sort_order_coffeeitem_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beanitem",
            name="highlight",
            field=models.CharField(blank=True, max_length=100, verbose_name="亮點標語"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="highlight",
            field=models.CharField(blank=True, max_length=100, verbose_name="亮點標語"),
        ),
    ]
