# Generated by Django 4.2.21 on 2026-08-15 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eshop", "0057_beanitem_highlight_coffeeitem_highlight_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="options_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_butter",
            field=models.BooleanField(default=False, verbose_name="黃油風味"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_caramel",
            field=models.BooleanField(default=False, verbose_name="焦糖風味"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_coconut",
            field=models.BooleanField(default=False, verbose_name="椰奶風味"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_green",
            field=models.BooleanField(default=False, verbose_name="綠茶"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_hojicha",
            field=models.BooleanField(default=False, verbose_name="焙茶"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_jasmine",
            field=models.BooleanField(default=False, verbose_name="茉莉花茶"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_matcha",
            field=models.BooleanField(default=False, verbose_name="抹茶"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_milk",
            field=models.BooleanField(default=False, verbose_name="奶類"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_oolong",
            field=models.BooleanField(default=False, verbose_name="烏龍茶"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_special",
            field=models.BooleanField(default=False, verbose_name="特調風味"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_topping",
            field=models.BooleanField(default=False, verbose_name="面層配料"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_vanilla",
            field=models.BooleanField(default=False, verbose_name="香草風味"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                (
                    "user",
                    "product_type",
                    "product_id",
                    "cup_level",
                    "milk_level",
                    "strength_level",
                    "grinding_level",
                    "weight",
                    "options_json",
                )
            },
        ),
    ]
