# Generated by Django 4.2.21 on 2026-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0058_alter_cartitem_unique_together_cartitem_options_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_milk_level",
            field=models.BooleanField(
                default=False, verbose_name="奶量（少/正常/追加）"
            ),
        ),
    ]
