# Generated by Django 4.2.21 on 2026-08-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0059_coffeeitem_option_milk_level_ordermodel_pickup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_bean_blend",
            field=models.BooleanField(default=False, verbose_name="配豆"),
        ),
        migrations.AlterField(
            model_name="coffeeitem",
            name="option_butter",
            field=models.BooleanField(default=False, verbose_name="黃油"),
        ),
        migrations.AlterField(
            model_name="coffeeitem",
            name="option_caramel",
            field=models.BooleanField(default=False, verbose_name="焦糖"),
        ),
        migrations.AlterField(
            model_name="coffeeitem",
            name="option_coconut",
            field=models.BooleanField(default=False, verbose_name="椰奶"),
        ),
        migrations.AlterField(
            model_name="coffeeitem",
            name="option_special",
            field=models.BooleanField(default=False, verbose_name="特調"),
        ),
        migrations.AlterField(
            model_name="coffeeitem",
            name="option_vanilla",
            field=models.BooleanField(default=False, verbose_name="香草"),
        ),
    ]
