# Generated by Django 4.2.21 on 2026-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0060_coffeeitem_option_bean_blend_ordermodel_pickup_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_cup_level",
            field=models.BooleanField(default=True, verbose_name="杯量"),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_strength_level",
            field=models.BooleanField(default=True, verbose_name="濃度"),
        ),
    ]
