# Generated by Django 4.2.21 on 2026-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0061_coffeeitem_option_cup_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_group_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='填選項組 key 的順序陣列（JSON），如 ["cup_level", "milk", "caramel", "topping"]；未列出的組按預設順序排在後。可用 key：cup_level、strength_level、milk_level、milk、caramel、butter、coconut、vanilla、special、oolong、jasmine、matcha、green、hojicha、topping、bean_blend',
                verbose_name="自訂選項組排序",
            ),
        ),
    ]
