# Generated by Django 4.2.21 on 2026-08-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0063_remove_coffeeitem_option_group_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例：Sticker 1", max_length=50, verbose_name="名稱"
                    ),
                ),
                (
                    "bg_image",
                    models.CharField(
                        choices=[
                            ("sticker_v1", "Sticker 1 背景（sticker_v1.png）"),
                            ("sticker_v2", "Sticker 2 背景（sticker_v2.png）"),
                            ("sticker_v3", "Sticker 3 背景（sticker_v3.png）"),
                            ("sticker", "Sticker 4 背景（sticker.png）"),
                        ],
                        default="sticker_v1",
                        max_length=50,
                        verbose_name="背景款式",
                    ),
                ),
                (
                    "front_image_preset",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "不使用內建前圖（改用上方上傳的自訂圖）"),
                            ("takeaway_cup", "咖啡杯（takeaway_cup.png）"),
                            ("float_bean", "咖啡豆（float_bean.png）"),
                            ("_takeaway_cup", "咖啡杯變體 A（_takeaway_cup.png）"),
                            ("__takeaway_cup", "咖啡杯變體 B（__takeaway_cup.png）"),
                        ],
                        default="takeaway_cup",
                        help_text="選擇內建前圖；若要使用下方上傳的自訂前圖，請選「不使用內建前圖」。",
                        max_length=50,
                        verbose_name="內建前圖款式",
                    ),
                ),
                (
                    "front_image",
                    models.ImageField(
                        blank=True,
                        help_text="上傳自訂去背 PNG 前圖；有值時優先於內建款式。注意：Render 免費方案重新部署後上傳檔案可能遺失（與現有商品圖相同限制）。",
                        null=True,
                        upload_to="stickers/",
                        verbose_name="自訂前圖（上傳）",
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        blank=True,
                        help_text="貼紙上半部小字。用 \\n 換行，例：Follow \\nYour Rhythm",
                        max_length=100,
                        verbose_name="英文副標題",
                    ),
                ),
                (
                    "text_zh",
                    models.CharField(
                        blank=True,
                        help_text="貼紙下半部大字。用 \\n 換行，例：5分鐘內\\n準備就緒!!",
                        max_length=100,
                        verbose_name="中文標語",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name_plural": "Stickers",
                "ordering": ["sort_order", "id"],
            },
        ),
        # pickup_time 既有 drift 修復（2026-08-24）：
        # 資料庫中 eshop_ordermodel.pickup_time 欄位已存在（0050 添加、0052 用
        # SeparateDatabaseAndState 只移除 Django state 保留資料庫欄位）；
        # 之後 model 又加回 DateTimeField 定義 → makemigrations 每次都誤判需 AddField。
        # 沿用 0052 手法：只更新 Django state，不動資料庫（欄位已存在，避免重複建立報錯）。
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="ordermodel",
                    name="pickup_time",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="取貨時間（舊版）"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="beanitem",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                help_text="選擇詳情頁顯示的貼紙；留空 = 不顯示。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eshop.sticker",
                verbose_name="Sticker 貼紙",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                help_text="選擇詳情頁顯示的貼紙；留空 = 不顯示。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eshop.sticker",
                verbose_name="Sticker 貼紙",
            ),
        ),
    ]
