# Generated by Django 4.2.21 on 2026-08-24 06:25
# Modified: Sticker 模組化 seed 資料（2026-08-24）
#
# Seed 4 款內建 Sticker + 設定現有商品關聯：
# - 現有咖啡全部 → Sticker 1（維持現況視覺：sticker_v1 + 咖啡杯 + Follow Your Rhythm）
# - 現有咖啡豆全部 → Sticker 2（維持現況視覺：sticker_v2 + 咖啡豆 + Crafting Perfection）
# - 管理員之後可在 admin 自由調整（含留空 = 不顯示）

from django.db import migrations


def seed_stickers(apps, schema_editor):
    Sticker = apps.get_model("eshop", "Sticker")
    CoffeeItem = apps.get_model("eshop", "CoffeeItem")
    BeanItem = apps.get_model("eshop", "BeanItem")

    stickers = {
        "s1": Sticker.objects.create(
            name="Sticker 1",
            bg_image="sticker_v1",
            front_image_preset="takeaway_cup",
            text_en="Follow \nYour Rhythm",
            text_zh="5分鐘內\n準備就緒!!",
            sort_order=1,
        ),
        "s2": Sticker.objects.create(
            name="Sticker 2",
            bg_image="sticker_v2",
            front_image_preset="float_bean",
            text_en="Crafting \nPerfection",
            text_zh="打造完美\n新鮮質量!",
            sort_order=2,
        ),
        "s3": Sticker.objects.create(
            name="Sticker 3",
            bg_image="sticker_v3",
            front_image_preset="_takeaway_cup",
            text_en="Take It \nEasy",
            text_zh="慢慢來\n也很快樂",
            sort_order=3,
        ),
        "s4": Sticker.objects.create(
            name="Sticker 4",
            bg_image="sticker",
            front_image_preset="__takeaway_cup",
            text_en="Freshly \nRoasted",
            text_zh="新鮮烘焙\n每日現做",
            sort_order=4,
        ),
    }

    # 現有商品預設關聯（維持現況視覺；管理員之後可自行調整）
    CoffeeItem.objects.update(sticker=stickers["s1"])
    BeanItem.objects.update(sticker=stickers["s2"])


def unseed_stickers(apps, schema_editor):
    Sticker = apps.get_model("eshop", "Sticker")
    CoffeeItem = apps.get_model("eshop", "CoffeeItem")
    BeanItem = apps.get_model("eshop", "BeanItem")
    CoffeeItem.objects.update(sticker=None)
    BeanItem.objects.update(sticker=None)
    Sticker.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0064_sticker_ordermodel_pickup_time_beanitem_sticker_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_stickers, unseed_stickers),
    ]

