# Generated by Django 4.2.21 on 2026-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0065_seed_sticker_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="staff_comment_1",
            field=models.CharField(
                blank=True,
                help_text="詳情頁照片左側氣泡（pattern-1）；建議 5~7 字，留空=不顯示",
                max_length=30,
                verbose_name="氣泡文字 1（左側）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="staff_comment_2",
            field=models.CharField(
                blank=True,
                help_text="詳情頁照片右下氣泡（pattern-2）；建議 5~7 字，留空=不顯示",
                max_length=30,
                verbose_name="氣泡文字 2（右下）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="staff_comment_3",
            field=models.CharField(
                blank=True,
                help_text="詳情頁照片右上氣泡（pattern-5）；建議 5~6 字，留空=不顯示",
                max_length=30,
                verbose_name="氣泡文字 3（右上）",
            ),
        ),
    ]
