# Generated by Django 4.2.21 on 2026-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0067_seed_staff_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_photo_ratio",
            field=models.FloatField(
                blank=True,
                help_text="例 860×1100 → 0.782；氣泡覆蓋層用此比例對齊照片；留空=存檔時自動量測",
                null=True,
                verbose_name="照片寬高比（寬÷高）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_safe_left",
            field=models.FloatField(
                blank=True,
                help_text="去背照片實際內容的左緣（占照片寬 %）；留空=存檔時自動量測",
                null=True,
                verbose_name="氣泡左基準（內容左緣 %）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_safe_right",
            field=models.FloatField(
                blank=True,
                help_text="去背照片實際內容的右緣（占照片寬 %）；留空=存檔時自動量測",
                null=True,
                verbose_name="氣泡右基準（內容右緣 %）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_scale",
            field=models.FloatField(
                blank=True,
                help_text="1=直式照片標準；橫式照片自動設為 1/寬高比（如 1200×840 → 0.7）避免氣泡相對照片過大；留空=存檔時自動計算",
                null=True,
                verbose_name="氣泡尺寸倍率",
            ),
        ),
    ]
