# Generated by Django 4.2.21 on 2026-09-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0069_fill_bubble_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_anim_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pop", "彈出（旋轉縮放；預設）"),
                    ("slide", "杯外滑入（沿所在側水平滑入）"),
                    ("rise", "下方浮升（垂直浮升＋淡入）"),
                ],
                default="",
                help_text="留空＝彈出（pop）；三種樣式只差在進場路徑，靜止位置相同",
                max_length=12,
                verbose_name="氣泡動畫 1（左側）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_anim_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pop", "彈出（旋轉縮放；預設）"),
                    ("slide", "杯外滑入（沿所在側水平滑入）"),
                    ("rise", "下方浮升（垂直浮升＋淡入）"),
                ],
                default="",
                help_text="留空＝彈出（pop）；三種樣式只差在進場路徑，靜止位置相同",
                max_length=12,
                verbose_name="氣泡動畫 2（右下）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_anim_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pop", "彈出（旋轉縮放；預設）"),
                    ("slide", "杯外滑入（沿所在側水平滑入）"),
                    ("rise", "下方浮升（垂直浮升＋淡入）"),
                ],
                default="",
                help_text="留空＝彈出（pop）；三種樣式只差在進場路徑，靜止位置相同",
                max_length=12,
                verbose_name="氣泡動畫 3（右上）",
            ),
        ),
    ]
