# Generated by Django 4.2.21 on 2026-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0069_fill_bubble_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dx_1",
            field=models.FloatField(
                blank=True,
                help_text="正值=往右、負值=往左；留空=預設位置（照片左側杯外）",
                null=True,
                verbose_name="氣泡 1 水平偏移（% 照片寬）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dx_2",
            field=models.FloatField(
                blank=True,
                help_text="正值=往右、負值=往左；留空=預設位置（照片右下杯外）",
                null=True,
                verbose_name="氣泡 2 水平偏移（% 照片寬）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dx_3",
            field=models.FloatField(
                blank=True,
                help_text="正值=往右、負值=往左；留空=預設位置（照片右上杯外）",
                null=True,
                verbose_name="氣泡 3 水平偏移（% 照片寬）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dy_1",
            field=models.FloatField(
                blank=True,
                help_text="正值=往下、負值=往上；預設 64%（手機 78%）→ 想更高就填負值",
                null=True,
                verbose_name="氣泡 1 垂直偏移（% 照片高）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dy_2",
            field=models.FloatField(
                blank=True,
                help_text="正值=往下、負值=往上；預設 80%（手機 84%）",
                null=True,
                verbose_name="氣泡 2 垂直偏移（% 照片高）",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_dy_3",
            field=models.FloatField(
                blank=True,
                help_text="正值=往下、負值=往上；預設 39.58%（手機 67.42%）",
                null=True,
                verbose_name="氣泡 3 垂直偏移（% 照片高）",
            ),
        ),
    ]
