# Generated by Django 4.2.21 on 2026-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0069_fill_bubble_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_pos_1",
            field=models.CharField(
                choices=[
                    ("tl", "左上"),
                    ("ml", "左中間"),
                    ("bl", "左下"),
                    ("tr", "右上"),
                    ("mr", "右中間"),
                    ("br", "右下"),
                ],
                default="ml",
                help_text="預設＝左中間（原設計位置）",
                max_length=2,
                verbose_name="氣泡 1 位置",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_pos_2",
            field=models.CharField(
                choices=[
                    ("tl", "左上"),
                    ("ml", "左中間"),
                    ("bl", "左下"),
                    ("tr", "右上"),
                    ("mr", "右中間"),
                    ("br", "右下"),
                ],
                default="br",
                help_text="預設＝右下（原設計位置）",
                max_length=2,
                verbose_name="氣泡 2 位置",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="bubble_pos_3",
            field=models.CharField(
                choices=[
                    ("tl", "左上"),
                    ("ml", "左中間"),
                    ("bl", "左下"),
                    ("tr", "右上"),
                    ("mr", "右中間"),
                    ("br", "右下"),
                ],
                default="tr",
                help_text="預設＝右上（原設計位置）",
                max_length=2,
                verbose_name="氣泡 3 位置",
            ),
        ),
    ]
