# Generated by Django 4.2.21 on 2026-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0070_coffeeitem_bubble_pos_1_coffeeitem_bubble_pos_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beanitem",
            name="option_grinding_level",
            field=models.BooleanField(default=True, verbose_name="選項組：研磨"),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="option_order_grinding_level",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="數字越小越靠前，0=預設",
                verbose_name="研磨順序",
            ),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="option_order_origin",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="數字越小越靠前，0=預設",
                verbose_name="產地順序",
            ),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="option_order_roast_level",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="數字越小越靠前，0=預設",
                verbose_name="烘焙度順序",
            ),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="option_origin",
            field=models.BooleanField(default=True, verbose_name="選項組：產地"),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="option_roast_level",
            field=models.BooleanField(default=False, verbose_name="選項組：烘焙度"),
        ),
        migrations.AddField(
            model_name="beanitem",
            name="origin_custom",
            field=models.CharField(
                blank=True,
                help_text="僅當產地選「其他（自填）」時使用",
                max_length=50,
                verbose_name="產地（其他自填）",
            ),
        ),
        migrations.AlterField(
            model_name="beanitem",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ET", "埃塞俄比亞"),
                    ("JP", "日本"),
                    ("CO", "哥倫比亞"),
                    ("BR", "巴西"),
                    ("GT", "危地馬拉"),
                    ("CR", "哥斯大黎加"),
                    ("KE", "肯亞"),
                    ("ID", "印尼"),
                    ("PE", "秘魯"),
                    ("PA", "巴拿馬"),
                    ("RW", "盧安達"),
                    ("HN", "宏都拉斯"),
                    ("TW", "台灣"),
                    ("CN-YN", "雲南"),
                    ("OT", "其他（自填）"),
                ],
                help_text="下拉選單；選「其他（自填）」時請填下方「產地（其他自填）」",
                max_length=50,
                verbose_name="產地（選項組值）",
            ),
        ),
    ]
