# Generated by Django 4.2.21 on 2026-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0072_bean_origin_normalize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beanitem",
            name="option_order_origin",
        ),
        migrations.RemoveField(
            model_name="beanitem",
            name="option_order_roast_level",
        ),
        migrations.RemoveField(
            model_name="beanitem",
            name="option_roast_level",
        ),
        migrations.AlterField(
            model_name="beanitem",
            name="option_origin",
            field=models.BooleanField(default=True, verbose_name="顯示產地"),
        ),
    ]
