# Generated by Django 4.2.21 on 2026-10-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0078_coffee_index_image_butterking"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_order_roast_level",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="數字越小越靠前，0=預設",
                verbose_name="烘焙順序",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_roast_level",
            field=models.BooleanField(default=False, verbose_name="烘焙"),
        ),
    ]
