# Generated by Django 4.2.21 on 2026-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop", "0079_coffeeitem_option_order_roast_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeitem",
            name="option_order_tea_type",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="數字越小越靠前，0=預設",
                verbose_name="茶種順序",
            ),
        ),
        migrations.AddField(
            model_name="coffeeitem",
            name="option_tea_type",
            field=models.BooleanField(default=False, verbose_name="茶種"),
        ),
    ]
