# Generated by Django 4.2.4 on 2025-02-20 14:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('origin', models.CharField(blank=True, max_length=30)),
                ('roast_level', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Dark')], default='M', max_length=1)),
                ('flavor', models.TextField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_shop_hot_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('origin', models.CharField(blank=True, max_length=30)),
                ('flavor', models.TextField(blank=True, max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cup_level', models.CharField(choices=[('L', 'Small'), ('M', 'Medium'), ('D', 'Large')], default='M', max_length=1)),
                ('milk_level', models.CharField(choices=[('L', 'Small'), ('M', 'Medium'), ('D', 'Large')], default='M', max_length=1)),
                ('is_published', models.BooleanField(default=True)),
                ('is_shop_hot_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('bean_items', models.ManyToManyField(blank=True, related_name='bean_orders', to='eshop.beanitem')),
                ('items', models.ManyToManyField(blank=True, related_name='coffee_orders', to='eshop.coffeeitem')),
            ],
        ),
    ]
