# Generated by Django 4.2.4 on 2025-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='bean_items',
        ),
        migrations.AlterField(
            model_name='beanitem',
            name='roast_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Deep')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='milk_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
