# Generated by Django 4.2.4 on 2025-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_remove_ordermodel_bean_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanitem',
            name='image',
            field=models.ImageField(upload_to='bean_images/'),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='image',
            field=models.ImageField(upload_to='coffee_images/'),
        ),
    ]
