# Generated by Django 4.2.4 on 2025-02-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_ordermodel_created_at_ordermodel_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
