# Generated by Django 4.2.4 on 2025-02-23 10:57

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('eshop', '0001_initial'),  # Depends on the previous migration
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE eshop_ordermodel ADD COLUMN total_price NUMERIC(10, 2);',
            reverse_sql='ALTER TABLE eshop_ordermodel DROP COLUMN total_price;',
        ),
    ]