# Generated by Django 4.2.4 on 2025-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_alter_coffeeitem_milk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeitem',
            name='cup_level',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('D', 'Large')], default='M', max_length=1),
        ),
    ]
