# Generated by Django 4.2.4 on 2025-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_alter_coffeeitem_cup_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanitem',
            name='roast_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Deep')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='cup_level',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='milk_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('E', 'Extra')], default='M', max_length=10),
        ),
    ]
