# Generated by Django 4.2.4 on 2025-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_alter_beanitem_roast_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanitem',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
