# Generated by Django 4.2.4 on 2025-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_ordermodel_cup_size_ordermodel_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
