# Generated by Django 4.2.4 on 2025-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_alter_ordermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_quick_order',
            field=models.BooleanField(default=False, help_text='标记是否为快速订单（早晨专用）', verbose_name='快速订单'),
        ),
    ]
