# Generated by Django 4.2.4 on 2025-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_ordermodel_is_quick_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='is_quick_order',
            field=models.BooleanField(default=False, help_text='優先處理', verbose_name='快速訂單'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('normal', '普通訂單'), ('quick', '快速訂單')], default='normal', max_length=10),
        ),
    ]
