# Generated by Django 4.2.4 on 2025-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_alter_ordermodel_is_quick_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beanitem',
            options={'verbose_name_plural': 'Bean'},
        ),
        migrations.AlterModelOptions(
            name='coffeeitem',
            options={'verbose_name_plural': 'Coffee'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
