# Generated by Django 4.2.4 on 2025-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0020_alter_ordermodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanitem',
            name='roast_level',
            field=models.CharField(choices=[('Non', 'Non'), ('Light', 'Light'), ('Medium', 'Medium'), ('Deep', 'Deep')], default='Non', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
    ]
