# Generated by Django 4.2.21 on 2025-08-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0025_rename_roast_level_cartitem_grinding_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beanitem',
            name='price',
        ),
    ]
