# Generated by Django 4.2.21 on 2025-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0029_alter_cartitem_options_alter_ordermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
