# Generated by Django 4.2.21 on 2025-09-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0031_fix_duplicate_pickup_codes'),
    ]

    operations = [
    ]
