# Generated by Django 4.2.21 on 2025-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0032_fix_duplicate_pickup_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('preparing', '制作中'), ('ready', '已就緒'), ('completed', '已完成')], default='pending', max_length=20),
        ),
    ]
