# Generated by Django 4.2.21 on 2025-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0034_beanitem_image_index_coffeeitem_image_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beanitem',
            options={'ordering': ['hot_item_order', '-list_date'], 'verbose_name_plural': 'Bean'},
        ),
        migrations.AlterModelOptions(
            name='coffeeitem',
            options={'ordering': ['hot_item_order', '-list_date'], 'verbose_name_plural': 'Coffee'},
        ),
        migrations.AddField(
            model_name='beanitem',
            name='hot_item_order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序'),
        ),
        migrations.AddField(
            model_name='coffeeitem',
            name='hot_item_order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小显示越靠前', verbose_name='热门商品排序'),
        ),
    ]
