# Generated by Django 4.2.21 on 2025-10-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0035_alter_beanitem_options_alter_coffeeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='fps_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='FPS二维码'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fps_reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FPS参考编号'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('alipay', '支付宝'), ('paypal', 'PayPal'), ('fps', 'FPS转数快'), ('cash', '现金支付')], default='alipay', max_length=10, verbose_name='支付方式'),
        ),
    ]
