# Generated by Django 4.2.21 on 2025-11-09 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0037_alter_ordermodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanitem',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coffeeitem',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
